spring:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  jpa:
    properties:
      hibernate:
        default_schema: public
        open-in-view: false
        show_sql: true

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:java.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password

logging:
  level:
    web: error