spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432:5432/huntersecurity?autoReconnect=true"&"useSSL=false
    username: huntersecurity
    password: huntersecurity

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  jpa:
    properties:
      hibernate:
        default_schema: public
        open-in-view: false
        show_sql: true

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:java.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password

logging:
  level:
    web: error