version: '3'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: huntersecurity
      POSTGRES_USER: huntersecurity
      POSTGRES_PASSWORD: huntersecurity
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/huntersecurity
      KC_DB_USERNAME: huntersecurity
      KC_DB_PASSWORD: huntersecurity
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    command: start-dev

volumes:
  postgres_data: